export const Scenes: any={
    Boot: "BootScene",
    Orientation: "OrientationScene",
    Preload: "PreloadScene",
    Game1: "Game1Scene",
    Game2: "Game2Scene",
    Game3: "Game3Scene",
    Game4: "Game4Scene",
    Game5: "Game5Scene",
    Game6: "Game6Scene",
    Game7: "Game7Scene",
    Game8: "Game8Scene",
    Game9: "Game9Scene",
    Game10: "Game10Scene",
    Game11: "Game11Scene",
    Game12: "Game12Scene",
}